name: FlaskSimpleAuth documentation publication on GitHub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install .[doc]
      - name: Check documentation syntax
        run: make check.docs
      - name: Generate documentation
        run: |
          make -C docs html
          ln -s docs/_build/html _site
      - name: Fix permissions
        run: |
          find docs/_build -type d -print | xargs chmod a+rx
          find docs/_build -type f -print | xargs chmod a+r
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
  deploy:
    needs: build
    environement:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
