name: FlaskSimpleAuth Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "pypy3.10" ]
    steps:
    # General Setup
    - name: Packages
      run: sudo apt install python3-dev libldap-dev libsasl2-dev gcc
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Set up Redis
      uses: supercharge/redis-github-action@1.4.0
    - name: Set up Memcached
      uses: niden/actions-memcached@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install Python Dependencies
      run: |
        pip install -U pip
        pip install -e .[dev,tests,demo,password,jwt,cors,httpauth,redis,memcached]
        pip install python-ldap ldap3
    # Checks
    - name: Check with pyright
      run: make check.pyright
    - name: Check with ruff
      run: make check.ruff
    - name: Check with flake8
      run: make check.flake8
    - name: Check with pytest
      run: make check.pytest
    - name: Check with coverage
      run: make check.coverage
