name: FlaskSimpleAuth Package

on:
  push:
    branches: [ main ]
  # push_request: ?

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # FIXME although pypy 3.10 seems to exist, github actions do not know that
        # 3.12 mypy: TypeError: type 'typing.TypeVar' is not an acceptable base type
        # TODO "3.12-dev"
        python-version: [ "3.10", "3.11" ]
    steps:
    # Setup
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Set up Redis
      uses: supercharge/redis-github-action@1.4.0
    - name: Set up Memcached
      uses: niden/actions-memcached@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    # Dependencies
    - name: Install Python Dependencies
      run: |
        pip install -U pip
        pip install -e .[dev,tests,demo,password,jwt,cors,httpauth,redis,memcached]
    # Checks
    - name: Check with mypy
      run: make check.mypy
    # FIXME unwanted changes, should be filtered with "# fmt:" tags
    # - name: Check with black
    #   run: black --check CacheToolsUtils.py
    - name: Check with flake8
      run: make check.flake8
    - name: Check with pytest
      run: make check.pytest
    - name: Check with coverage
      run: make check.coverage
